### ISSUE TITLE
can't connect to vast-ai

### ISSUE THREAD

**Issue by JackBekket** [JackBekket/Reflexia#12]
![image](https://github.com/user-attachments/assets/0817b117-e277-4737-ae82-b64dadeb4198)

**Comment by mintyleaf** [comment]
<img width="339" alt="Screenshot 2024-09-24 at 05 27 15" src="https://github.com/user-attachments/assets/0448bdca-908b-410f-85ee-b9d06911a3b1">
<img width="624" alt="Screenshot 2024-09-24 at 05 27 40" src="https://github.com/user-attachments/assets/8d69bdef-6c82-4143-aec8-10cb3ee0feed">

seems like you forgot http:// since it validates any provided input
